### ISSUE TITLE
Warning: openssl_decrypt on line 25

### ISSUE THREAD

**Issue by eArabic** [halojoy/QuickCommunity#1]
Hello
Thank you very much for the script, it came to me wrong what is the reason and what is the solution.

**Warning: openssl_decrypt(): IV passed is only 5 bytes long, cipher expects an IV of precisely 8 bytes, padding with \0 in /membri/QuickerBB/Quick/core/classSession.php on line 25**

**Warning: openssl_encrypt(): IV passed is only 5 bytes long, cipher expects an IV of precisely 8 bytes, padding with \0 in /membri//QuickerBB/Quick/core/classSession.php on line 62**

**Comment by halojoy** [comment]
I dont understand why you can get this error.
The IV is generated in setup. It is done with 8 bytes.
So why you get only 5 bytes is a mystery.

You can have a look at **QuickCommunity - classSession.php LINE 15**.
The value should be 8 bytes.
You can add some chars, to make it 8 bytes.

**Comment by eArabic** [comment]
Thank you very much The issue has been resolved by adding:
```
private $ secret = '12345678';
private $ iv = '12345678';
```
Forum is very good light quick, but there is a problem dealing with the css 
Any modification does not appear and does not work against a forum QuickerBB Edit css is easy.
Thank you so much

**Comment by eArabic** [comment]
What does this error mean and what is the solution

`Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /membri/user1/Full/AAA/v/Quick/core/classAction.php:162) in /membri/user1/Full/AAA/v/Quick/inc/register.php on line 22`

**Comment by halojoy** [comment]
It is because I have put session_start in the scripts.
But I have changed this now.
I put the session_start iin beginning of core/init.php
This should do it.

Now, you really should do a fresh install of Quick Community.
Take the latest release.
I have done some fixes.

**Comment by eArabic** [comment]
Hello dear friend
I have the problem again What is the solution?
Warning: openssl_decrypt(): IV passed is only 5 bytes long, cipher expects an IV of precisely 16 bytes, padding with \0 in /membri/host/web/QuickCommunity-2.01/core/classSession.php on line 31
Warning: openssl_encrypt(): IV passed is only 5 bytes long, cipher expects an IV of precisely 16 bytes, padding with \0 in /membri/host/web/QuickCommunity-2.01/core/classSession.php on line 116

**Comment by monsterprg** [comment]
use this : 


<pre>$data = "TEST";

$key = "YOUR_KEY";

$encryption_key=base64_decode($key);

$iv=openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));

$encrypted=openssl_encrypt($data,'aes-256-cbc',$encryption_key,0,$iv);
</pre>



if not work/work please reply me 👌

Sorry if my english have mistakes
i can't speak english😃
