### ISSUE TITLE
Please add  Locked and sticky posts

### ISSUE THREAD

**Issue by eArabic** [halojoy/QuickCommunity#3]
Hello
Please try adding these features:
mobile browsing.
Editing css is easy, I noticed that I'm fairest and the edit does not appear.
The settings should limit the number of posts that will appear on the page.
Search
Pagination
Locked and sticky posts
Link feature does not work It is one for all posts:
/?act=post&pid=$n | $n : 1,2,3,4,5,.....
There should be a code that distinguishes the post from other posts.
When a Post Reply to an article should be returned to the post page automatically.
thank you very much

**Comment by halojoy** [comment]
I added Sticky topics.
This is a feature in the Admin panel.

My thinking about return after post, was that the poster wants to see his post.
If there are many posts in the page, the post will be at bottom and not visable.

**Comment by eArabic** [comment]
Thank you very much for the update, but I returned this problem when I reinstalled:

INSTALL step 3
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setkey' in 'field list'' in /membri/User_452687/QuickCommunity-2.07/setup/setup3.php:73 Stack trace: #0 /membri/User_452687/QuickCommunity-2.07/setup/setup3.php(73): PDO->exec('INSERT INTO set...') #1 /membri/User_452687/QuickCommunity-2.07/setup.php(16): require('/membri/User_452687...') #2 {main} thrown in /membri/User_452687/QuickCommunity-2.07/setup/setup3.php on line 73




Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setkey' in 'field list'' in /membri/User_452687/QuickCommunity-2.07/core/classDatabase.php:25 Stack trace: #0 /membri/User_452687/QuickCommunity-2.07/core/classDatabase.php(25): PDO->prepare('SELECT setkey, ...') #1 /membri/User_452687/QuickCommunity-2.07/core/classDatabase.php(288): Database->querySQL('SELECT setkey, ...') #2 /membri/User_452687/QuickCommunity-2.07/core/classDatabase.php on line 25

**Comment by halojoy** [comment]
I will look into this setup3.php Line 73 problem.
The strange thing is I do not get this error.

It is probably due to the CREATE TABLE did not work.
Files data/tables_mysql.php and tables_sqlite.php
What database do you use?

**Comment by halojoy** [comment]
I have added Locked Topics.  In the admin.
Only admin can post in a locked topic.

**Comment by eArabic** [comment]
Hello my friend
The reason for the error 73 database may exist earlier and do not add the updated fields. (setkey)
When the installation is new, if the database is updated, delete the old and install again

**Comment by eArabic** [comment]
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.6.33-log - MySQL Community Server (GPL)
Protocol version: 10
User: root360@localhost
Server charset: UTF-8 Unicode (utf8)
Web server
Apache
Database client version: libmysql - 5.6.33
phpMyAdmin
Version information: 4.1.7
